Repository when-where/whenwhere-client, pull requests merged in 2023-07, with the labels that each got.

#24 프로필 설정 및 회원가입 모달
  src/apis/index.ts
  src/apis/user.ts
  src/components/buttons/ButtonMain.tsx
  src/components/inputs/InputProfile.tsx
  src/screens/Navigation.tsx
  src/screens/auth/CreateProfileScreen.tsx
  src/screens/auth/EmailAuthenticationScreen.tsx
  src/screens/auth/MakeProfileScreen.tsx
  src/screens/auth/SignInScreen.tsx
  src/screens/auth/SignUpScreen.tsx
  src/screens/index.ts
  src/states/userState.ts
  src/types/auth.ts
  src/utils/randomProfileColor.ts
Labels: feat, fix, rename, refactor, style

#26 프로필 API 수정
  src/apis/user.ts
Labels: refactor

#27 카카오 로그인 기능
  src/screens/Navigation.tsx
  src/screens/auth/AuthScreen.tsx
  src/screens/auth/EmailAuthenticationScreen.tsx
  src/screens/auth/KakaoWebViewScreen.tsx
  src/screens/index.ts
  src/types/auth.ts
Labels: feat, style

#31 husky 설정 수정
  package.json
Labels: fix, setting

#33 약속 보기
  package-lock.json
  package.json
  src/assets/icons/IconCalendar.tsx
  src/assets/icons/IconChat.tsx
  src/assets/icons/IconCreate.tsx
  src/assets/icons/IconGroup.tsx
  src/assets/icons/IconHamburger.tsx
  src/assets/icons/IconHome.tsx
  src/assets/icons/IconLocation.tsx
  src/assets/icons/IconNotification.tsx
  src/assets/icons/IconProfile.tsx
  src/assets/icons/IconSearch.tsx
  src/assets/icons/index.ts
  src/assets/themes/caption.ts
  src/assets/themes/globalColor.ts
  src/assets/themes/heading.ts
  src/assets/themes/label.ts
  src/assets/themes/paragraph.ts
  src/components/buttons/ButtonRound.tsx
  src/components/buttons/index.ts
  src/components/cards/CardPlan.tsx
  src/components/cards/index.ts
  src/components/labels/LabelAnswerState.tsx
  src/components/labels/LabelIconDetail.tsx
  src/components/labels/LabelPlanState.tsx
  src/components/labels/index.ts
  src/components/navigators/NavigatorBottom.tsx
  src/components/navigators/NavigatorTop.tsx
  src/components/navigators/index.ts
  src/screens/Navigation.tsx
  src/screens/group/MainGroupScreen.tsx
  src/screens/index.ts
  src/screens/plan/MainPlanScreen.tsx
  src/utils/metric.ts
Labels: feat, setting, style

#35 프로필 설정 기능
  src/apis/index.ts
  src/apis/user.ts
  src/components/navigators/NavigatorBottom.tsx
  src/screens/Navigation.tsx
  src/screens/auth/CreateProfileScreen.tsx
  src/screens/auth/KakaoWebViewScreen.tsx
  src/screens/auth/SignInScreen.tsx
  src/screens/auth/SignUpScreen.tsx
  src/states/userState.ts
  src/types/auth.ts
  src/types/navigation.ts
Labels: feat, refactor
