Repository when-where/whenwhere-client, pull requests merged in 2023-06, with the labels that each got.

#3 스플래시 스크린
  App.tsx
  android/app/src/main/java/com/longtimenosee/MainActivity.java
  android/app/src/main/res/layout/launch_screen.xml
  android/app/src/main/res/values/colors.xml
  package-lock.json
  package.json
Labels: feat

#7 스플래시 스크린(ios)
  ios/LongTimeNoSee.xcodeproj/project.pbxproj
  ios/LongTimeNoSee.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  ios/LongTimeNoSee/AppDelegate.mm
  ios/LongTimeNoSee/Images.xcassets/Contents.json
  ios/LongTimeNoSee/Images.xcassets/splash.imageset/Contents.json
  ios/LongTimeNoSee/Images.xcassets/splash.imageset/SP.png
  ios/LongTimeNoSee/Images.xcassets/splash.imageset/SP@2x.png
  ios/LongTimeNoSee/Images.xcassets/splash.imageset/SP@3x.png
  ios/LongTimeNoSee/LaunchScreen.storyboard
  ios/Podfile.lock
Labels: feat

#9 인트로 스크린&로그인 스크린
  .prettierignore
  App.tsx
  android/app/src/main/assets/fonts/GmarketSansBold.otf
  android/app/src/main/assets/fonts/GmarketSansLight.otf
  android/app/src/main/assets/fonts/GmarketSansMedium.otf
  android/app/src/main/assets/fonts/Pretendard-Bold.otf
  android/app/src/main/assets/fonts/Pretendard-Regular.otf
  android/app/src/main/assets/fonts/Pretendard-SemiBold.otf
  android/link-assets-manifest.json
  assets/fonts/GmarketSansBold.otf
  assets/fonts/GmarketSansLight.otf
  assets/fonts/GmarketSansMedium.otf
  assets/fonts/Pretendard-Bold.otf
  assets/fonts/Pretendard-Regular.otf
  assets/fonts/Pretendard-SemiBold.otf
  ios/LongTimeNoSee.xcodeproj/project.pbxproj
  ios/LongTimeNoSee/Info.plist
  ios/link-assets-manifest.json
  package-lock.json
  package.json
  react-native.config.js
  src/assets/images/kakao_login.png
  src/assets/themes/caption.ts
  src/assets/themes/darkMode.ts
  src/assets/themes/globalColor.ts
  src/assets/themes/heading.ts
  src/assets/themes/index.ts
  src/assets/themes/label.ts
  src/assets/themes/lightMode.ts
  src/assets/themes/paragraph.ts
  src/components/button/ButtonMain.tsx
  src/components/button/ButtonText.tsx
  src/components/button/index.ts
  src/components/form/InputAuth.tsx
  src/components/form/index.ts
  src/screens/Navigation.tsx
  src/screens/auth/AuthScreen.tsx
  src/screens/auth/SignInScreen.tsx
  src/screens/index.ts
  tsconfig.json
Labels: feat, setting, style

#10 회원가입 스크린
  declarations.d.ts
  ios/LongTimeNoSee.xcodeproj/project.pbxproj
  ios/Podfile.lock
  metro.config.js
  package-lock.json
  package.json
  src/assets/icons/CheckFalseGray.tsx
  src/assets/icons/CheckFalsePrimary.tsx
  src/assets/icons/CheckTrue.tsx
  src/assets/themes/caption.ts
  src/components/button/index.ts
  src/components/buttons/ButtonAssist.tsx
  src/components/buttons/ButtonCheckbox.tsx
  src/components/buttons/ButtonMain.tsx
  src/components/buttons/ButtonText.tsx
  src/components/buttons/index.ts
  src/components/inputs/InputAuth.tsx
  src/components/inputs/InputProfile.tsx
  src/components/inputs/index.ts
  src/screens/Navigation.tsx
  src/screens/auth/AuthScreen.tsx
  src/screens/auth/EmailAuthenticationScreen.tsx
  src/screens/auth/MakeProfileScreen.tsx
  src/screens/auth/SignInScreen.tsx
  src/screens/auth/SignUpScreen.tsx
  src/screens/index.ts
  tsconfig.json
Labels: rename, setting, style

#13 themes 파일 수정 및 Button 컴포넌트 수정
  .eslintrc.js
  src/assets/themes/caption.ts
  src/assets/themes/heading.ts
  src/assets/themes/label.ts
  src/assets/themes/paragraph.ts
  src/components/buttons/ButtonMain.tsx
  src/components/buttons/ButtonText.tsx
  src/components/buttons/index.ts
  src/components/inputs/InputAuth.tsx
  src/screens/auth/AuthScreen.tsx
  src/screens/auth/EmailAuthenticationScreen.tsx
  src/screens/auth/MakeProfileScreen.tsx
  src/screens/auth/SignInScreen.tsx
  src/screens/auth/SignUpScreen.tsx
Labels: refactor, style

#15 라이브러리 추가 및 env 설정
  babel.config.js
  env.d.ts
  package-lock.json
  package.json
  src/apis/index.ts
  tsconfig.json
Labels: setting

#18 axios instance baseURL 수정
  src/apis/index.ts
Labels: bug, fix

#20 회원가입 기능
  .eslintrc.js
  src/apis/auth.ts
  src/components/buttons/ButtonCheckbox.tsx
  src/components/buttons/ButtonMain.tsx
  src/components/inputs/InputAuth.tsx
  src/components/inputs/index.ts
  src/screens/Navigation.tsx
  src/screens/auth/EmailAuthenticationScreen.tsx
  src/screens/auth/MakeProfileScreen.tsx
  src/screens/auth/SignUpScreen.tsx
  src/types/auth.ts
  src/types/error.ts
  src/types/index.ts
  src/types/navigation.ts
Labels: feat, fix, setting

#21 로컬 로그인 기능
  package-lock.json
  package.json
  src/apis/auth.ts
  src/apis/index.ts
  src/screens/Navigation.tsx
  src/screens/auth/AuthScreen.tsx
  src/screens/auth/SignInScreen.tsx
  src/screens/plan/MainPlanScreen.tsx
  src/states/userState.ts
  src/types/auth.ts
Labels: feat, refactor, setting
